spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sunlin
    password: 123456
    url: jdbc:mysql://47.94.128.132:3306/basicAuthorization?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  session:
    store-type: redis
    redis:
      namespace: oauthToken
  resources:
    static-locations: classpath:/resources/static,classpath:/resources
  redis:
    port: 6379
    host: 47.94.128.132
    password:

server:
  port: 8060

com:
  security:
    browser:
      login-type: JSON
      signUp: /demo-signUp.html
      loginOutUrl: /logout.html
      sessionInvalidUrl: /session-invalid.html
      staticAvoidPath: /static/**,/resources/**
    code:
      imgCode:
        length: 4
        width: 100
        height: 45
        url: /user,/user/*
      smsCode:
        length: 4
        expireIn: 600
        url: /auth/smsForm
    social:
      qq:
        app-id: 101477439
        app-secret: 1c9274f4c91af237a4055680a931cd71
        providerId: callback
      weixin:
        app-id: wxd888ff7ebaff0fdb
        app-secret: 771c5f039f324f38a1f18dcb744db897
        providerId: weixin
      filterProcessUrl: /qqLogin
    oauth:
      clients[0]:
        clientId: txhl
        clientSecret: txhlSecret
        accessTokenValiditySeconds: 3600
      clients[1]:
          clientId: test
          clientSecret: testSecret
          accessTokenValiditySeconds: 3600
      tokenStore: redis
      #storeType: jwt